name: uwdatasci420

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.6
  - scikit-learn=0.20.3
  - seaborn=0.10.0
  - category_encoders=2.0.0
  - joblib=0.14.1
  - imbalanced-learn=0.5.0
  - jupyter=1.0.0
  - ipykernel=5.1.4
  - mlxtend=0.17.2
  - graphviz=2.38
  - pip=19.0.1

  - pip:
    - pylint
